import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import ts from 'typescript';
const code=ts.transpileModule(await fs.readFile('lib/asset-library.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll("'./studio'","'./studio.mjs'");
await fs.writeFile('work/test/asset-library.mjs',code);
const {exampleProject,newProject,validateProject}=await import('../work/test/studio.mjs');
const {libraryEntries,sharedLibraryEntries,copyToProject,applyLibraryAsset,revisedAsset,duplicateGroups}=await import('../work/test/asset-library.mjs');
const p=exampleProject(), dest=newProject('第二个项目');dest.shots=structuredClone(p.shots);
assert.equal(sharedLibraryEntries([p]).length,0,'legacy and project-only assets stay out of reusable library');
const published=structuredClone(p);published.assets[0].inLibrary=true;
assert.equal(sharedLibraryEntries([published]).length,1);
const reusable=sharedLibraryEntries([published])[0];
assert.equal(copyToProject(dest,reusable).asset.inLibrary,false,'using a library asset does not republish the project copy');
const invalidFlag=structuredClone(p);invalidFlag.assets[0].inLibrary='yes';assert.throws(()=>validateProject(invalidFlag));
const invalidRef=structuredClone(p);invalidRef.assets[0].referenceImage={id:crypto.randomUUID(),url:'https://invalid.example/image',type:'image/png',name:'bad'};assert.throws(()=>validateProject(invalidRef));
const media={id:crypto.randomUUID(),url:'',name:'站位.png',type:'image/png'};media.url='/api/media/'+media.id;p.shots[0].blockingImage=media;
let all=libraryEntries([p]);assert.equal(all.filter(e=>e.asset.kind==='站位图').length,1);
const diagram=all.find(e=>e.shotId);const promoted=copyToProject(p,diagram);assert.equal(promoted.asset.kind,'站位图');assert.equal(libraryEntries([promoted.project]).filter(e=>e.asset.kind==='站位图').length,1,'promoted diagrams must not be counted twice');
const source=all[0];const cloned=copyToProject(dest,source);assert.notEqual(cloned.asset.id,source.asset.id);assert.equal(source.asset.origin,undefined);assert.equal(copyToProject(cloned.project,source).project.assets.length,1,'copying the same source should reuse the local asset');
const used=applyLibraryAsset(dest,source,'分镜',dest.shots[0].id);assert(used.shots[0].references.includes(used.assets[0].id));assert.equal(used.assets[0].usage[0].target,'分镜');assert.equal(dest.assets.length,0);
const staged=applyLibraryAsset(dest,diagram,'分镜',dest.shots[0].id);assert.equal(staged.shots[0].blockingImage.id,media.id);
assert.throws(()=>applyLibraryAsset(dest,source,'分镜','missing'));
const appended=applyLibraryAsset(dest,source,'故事');assert(appended.story.includes(source.asset.description));assert.equal(dest.story,'');
const edited=revisedAsset({...source.asset,image:media},{...source.asset,image:media,description:'新设定'});assert.equal(edited.versions[0].description,source.asset.description);assert.equal(edited.versions[0].image.id,media.id);assert.equal(edited.createdAt,undefined,'legacy creation dates must not be fabricated');
const tracked=revisedAsset(undefined,{...source.asset,id:crypto.randomUUID(),tags:['角色'],attributes:{物种:'猫'},favorite:true});assert(tracked.createdAt);
const test=structuredClone(p);test.assets.push(tracked);test.assets[0]=edited;validateProject(test);const invalid=structuredClone(test);invalid.assets[0].tags=Array(21).fill('标签');assert.throws(()=>validateProject(invalid));
const duplicate=structuredClone(p.assets[0]);duplicate.id=crypto.randomUUID();p.assets.push(duplicate);assert.equal(duplicateGroups(libraryEntries([p])).length,1);
console.log('PASS asset library: cross-project copy, reuse, linkage, diagram deduplication, version/media preservation and metadata validation');
