import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import ts from 'typescript';
const bundle={projectId:'project',tasks:[{id:'shot',title:'镜头2',prompt:'原提示词',model:'Seedance 2.0 Mini',ratio:'16:9',duration:10,references:[{mediaId:'a',label:'图1'},{mediaId:'b',label:'图2'}]}],media:[{id:'a',dataUrl:'data:image/png;base64,AQ=='},{id:'b',dataUrl:'data:image/png;base64,Ag=='}]};
const state={paused:false,accounts:[{id:'account',name:'测试',group:'A',enabled:true}],participatingAccountIds:['account'],jobs:[],settings:{}};
let cells=[],index=0,commands=[],submitted=0;
const jsx=(type,props)=>({type,props});
const manager={doubaoJobFailed:j=>j?.status==='failed',doubaoSubmissionAccounts:s=>{if(s.paused)throw Error('已暂停');return s.accounts.filter(a=>a.enabled&&s.participatingAccountIds.includes(a.id));},doubaoCommand:async(action='snapshot',body)=>{commands.push({action,body});if(action==='snapshot')return structuredClone(state);if(action==='previewJob')return {bundle:structuredClone(bundle),accountIds:['account']};return structuredClone(state);}};
const context={exports:{},require:name=>name==='react'?{useState:initial=>{const i=index++;if(!(i in cells))cells[i]=initial;return [cells[i],value=>{cells[i]=typeof value==='function'?value(cells[i]):value;}];},useRef:initial=>{const i=index++;return cells[i]??(cells[i]={current:initial});}}:name==='react/jsx-runtime'?{jsx,jsxs:jsx,Fragment:'Fragment'}:name==='@/lib/doubao'?{doubaoBundle:async()=>structuredClone(bundle)}:name==='@/lib/doubao-manager'?manager:new Proxy({},{get:(_,key)=>key})};
vm.runInNewContext(ts.transpileModule(await fs.readFile('components/doubao-task-preview.tsx','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,context);
const render=()=>{index=0;return context.exports.useDoubaoTaskPreview(()=>submitted++);};
function nodes(node){if(!node)return [];if(Array.isArray(node))return node.flatMap(nodes);if(typeof node!=='object')return [];return [node,...nodes(node.props?.children)];}
const button=(hook,label)=>nodes(hook.dialog).find(n=>n.type==='Button'&&String(n.props.children).includes(label));
let hook=render();await hook.open({id:'project'},['shot']);hook=render();
assert.equal(commands.some(c=>['enqueue','regenerate'].includes(c.action)),false,'opening preview never submits');
button(hook,'返回修改').props.onClick();hook=render();assert.equal(nodes(hook.dialog).find(n=>n.type==='Dialog').props.open,false,'cancel closes preview');
assert.equal(submitted,0);
await hook.open({id:'project'},['shot']);hook=render();
nodes(hook.dialog).find(n=>n.type==='textarea').props.onChange({target:{value:'用户核对后的提示词'}});hook=render();
button(hook,'确认提交').props.onClick();button(hook,'确认提交').props.onClick();
await new Promise(r=>setImmediate(r));
assert.equal(commands.filter(c=>c.action==='enqueue').length,1,'double click cannot enqueue twice');
assert.equal(commands.find(c=>c.action==='enqueue').body.bundle.tasks[0].prompt,'用户核对后的提示词');
assert.deepEqual(commands.find(c=>c.action==='enqueue').body.bundle.tasks[0].references,bundle.tasks[0].references,'preview upload order is submission order');
assert.equal(submitted,1);
hook=render();await hook.open({id:'project'},['shot']);hook=render();state.paused=true;button(hook,'确认提交').props.onClick();await new Promise(r=>setImmediate(r));hook=render();
assert.equal(commands.filter(c=>c.action==='enqueue').length,1,'pause between preview and confirmation blocks submission');
assert(nodes(hook.dialog).some(n=>n.props?.role==='alert'&&n.props.children==='已暂停'));
state.paused=false;button(hook,'返回修改').props.onClick();hook=render();await hook.open({id:'project'},[],{saved:true,retryId:'failed-job'});hook=render();button(hook,'确认提交').props.onClick();await new Promise(r=>setImmediate(r));
assert.equal(commands.filter(c=>c.action==='regenerate').length,1);assert.equal(commands.find(c=>c.action==='regenerate').body.id,'failed-job');
console.log('PASS preview/cancel without enqueue, exact edited prompt and reference order, duplicate confirmation, paused recheck and saved-job retry preview.');
