import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {validateBundle,safeName} from '../browser-extension/contract.js';
import {fillPrompt} from '../browser-extension/fill.js';
const dir='work/doubao-test';await fs.mkdir(dir,{recursive:true});
for(const name of ['video-generation','doubao-manager','doubao','studio','dialogue','dialogue-timeline','video-context','video-performance','video-request','video-voice']){const code=ts.transpileModule(await fs.readFile(`lib/${name}.ts`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");await fs.writeFile(`${dir}/${name}.mjs`,code);}
const imp=n=>import(pathToFileURL(path.resolve(dir,n+'.mjs')));const {newProject,newShot}=await imp('studio');const {doubaoTasks}=await imp('doubao');
const p=newProject();p.shots=[newShot()];const s=p.shots[0];s.character='石头';s.description='石头 ( @role_shitou ) 拿起 红笔 ( @prop_pen )。';s.dialogue='石头：“妈，今天回来呀。”';
p.assets=[['人物','石头'],['道具','红笔']].map(([kind,name],i)=>({id:'asset-'+i,kind,name,description:'固定设定',image:{id:'image-'+i,url:'/api/media/image-'+i,name:name+'.png',type:'image/png'}}));s.references=p.assets.map(a=>a.id);
const tasks=doubaoTasks(p,[s.id]);assert.equal(tasks.length,1);assert(tasks[0].prompt.includes('石头 ( @图1 )'));assert(tasks[0].prompt.includes('红笔 ( @图2 )'));assert(tasks[0].prompt.includes('不得出现任何文字'));assert(tasks[0].prompt.includes('不配背景音乐'));assert.equal(doubaoTasks(p,[]).length,0);
const b={format:'director-doubao-task',version:1,projectId:p.id,tasks:[{...tasks[0],references:[{mediaId:'image-0',label:'图1'}]}],media:[{id:'image-0',type:'image/png',dataUrl:'data:image/png;base64,AQID'}]};assert.equal(validateBundle(b),b);assert.throws(()=>validateBundle({...b,version:2}));assert.throws(()=>validateBundle({...b,media:[]}));assert.throws(()=>validateBundle({...b,media:[{...b.media[0],dataUrl:'https://bad.example/a.png'}]}));assert(!safeName('../a:b').includes('/'));
// Test the injected adapter without a live account or a paid submission.
globalThis.location={origin:'https://www.doubao.com'};globalThis.HTMLElement=class {};globalThis.HTMLTextAreaElement=class extends HTMLElement {get value(){return this.text||''}set value(v){this.text=v}getClientRects(){return [{}]}closest(){return null}getAttribute(){return null}focus(){}dispatchEvent(){}};
globalThis.InputEvent=class{};const editor=new HTMLTextAreaElement();globalThis.document={activeElement:editor,querySelectorAll:()=>[editor]};assert(fillPrompt('原台词').ok);assert.equal(editor.value,'原台词');assert.equal(fillPrompt('替换草稿').ok,false);assert.equal(editor.value,'原台词');document.activeElement=null;document.querySelectorAll=()=>[];assert.equal(fillPrompt('台词').ok,false);
const manifest=JSON.parse(await fs.readFile('browser-extension/manifest.json','utf8'));assert.equal(manifest.manifest_version,3);assert.deepEqual(manifest.host_permissions,['https://www.doubao.com/*','https://doubao.com/*','http://127.0.0.1/*']);assert(!manifest.permissions.includes('cookies'));
const {receiveDoubaoVideos}=await imp('doubao-manager');
const resultMedia={id:'generated-video',url:'/api/media/generated-video',name:'result.mp4',type:'video/mp4'};
const job={id:'doubao-job',projectId:p.id,shotId:s.id,status:'succeeded',media:resultMedia,originalVideoId:''};
const received=receiveDoubaoVideos(p,[job]);assert.equal(received.shots[0].video.id,resultMedia.id);assert.equal(receiveDoubaoVideos(received,[job]),received);
assert.equal(receiveDoubaoVideos(p,[{...job,projectId:'other'}]),p);
const manual={...p,shots:[{...s,video:{...resultMedia,id:'manual-upload'}}]};assert.equal(receiveDoubaoVideos(manual,[job]),manual,'manual replacement preserved');
const removed={...p,shots:[{...s,video:undefined,videoManualUpdatedAt:'2026-09-12T00:00:00.000Z'}]};
assert.equal(receiveDoubaoVideos(removed,[{...job,createdAt:'2026-09-11T23:59:00.000Z'}]),removed,'old Doubao results do not restore deleted video');
assert.equal(receiveDoubaoVideos(removed,[{...job,createdAt:'2026-09-12T00:01:00.000Z'}]).shots[0].video.id,resultMedia.id,'new Doubao tasks can return after deletion');
console.log('PASS Doubao task selection, ordered images, original dialogue restrictions, bundle validation, scoped permissions, input filling, draft preservation and exact/idempotent video return.');

const {doubaoSubmissionAccounts}=await imp('doubao-manager');
const selection={paused:false,participatingAccountIds:['a'],accounts:[{id:'a',group:'甲组',enabled:true},{id:'b',group:'甲组',enabled:true},{id:'c',group:'乙组',enabled:true}]};
assert.deepEqual(doubaoSubmissionAccounts(selection,'甲组').map(a=>a.id),['a']);
assert.throws(()=>doubaoSubmissionAccounts({...selection,paused:true}),/暂停/);
assert.throws(()=>doubaoSubmissionAccounts({...selection,participatingAccountIds:[]}),/调用/);
assert.throws(()=>doubaoSubmissionAccounts(selection,'乙组'),/调用/);
assert.throws(()=>doubaoSubmissionAccounts({...selection,accounts:selection.accounts.map(a=>({...a,enabled:false}))}),/调用/);
console.log('PASS frontend preflight for pause, missing participation, group mismatch and disabled accounts.');
const {doubaoJobPaused}=await imp('doubao-manager');
const {doubaoJobFailed}=await imp('doubao-manager');
assert.equal(doubaoJobFailed({status:'attention'}),true);
assert.equal(doubaoJobFailed({status:'failed'}),true);
for(const status of ['queued','paused','prepared','submitted','downloading','succeeded'])assert.equal(doubaoJobFailed({status}),false);
assert.equal(doubaoJobPaused({status:'queued'},true),true);
assert.equal(doubaoJobPaused({status:'paused'},true),true);
assert.equal(doubaoJobPaused({status:'prepared'},true),true);
assert.equal(doubaoJobPaused({status:'queued'},false),false);
for (const status of ['submitted','downloading','succeeded','failed','attention']) assert.equal(doubaoJobPaused({status,submittedAt:'2026-09-12'},true),false);
console.log('PASS synchronized paused display and truthful submitted-task status.');

const {doubaoParameters}=await imp('doubao');
const defaults={model:'Seedance 2.0 Mini',ratio:'9:16',duration:8};
const overrides={...s,doubaoModel:'Seedance 2.0 Fast',doubaoRatio:'4:3',duration:12};
assert.deepEqual(doubaoParameters(p,overrides,defaults),{model:'Seedance 2.0 Fast',ratio:'4:3',duration:12,resolution:'',sources:{model:'分镜',ratio:'分镜',duration:'分镜'}});
assert.equal(doubaoParameters(p,{...s,duration:0},defaults).duration,8);
assert.equal(doubaoParameters({...p,ratio:''},{...s,duration:0},defaults).ratio,'9:16');
assert.equal(doubaoParameters(p,s,defaults).model,defaults.model);
const tailored=doubaoTasks({...p,shots:[overrides]},[s.id],defaults)[0];
assert.equal(tailored.ratio,'4:3');assert.equal(tailored.duration,12);assert.equal(tailored.model,'Seedance 2.0 Fast');
assert(tailored.prompt.includes('画幅：4:3'));assert(tailored.prompt.includes('时长：12秒'));assert(!tailored.prompt.includes('NaN'));
console.log('PASS shot-first model/aspect/duration and explicit plugin defaults, prompt/request consistency.');

assert.equal(doubaoParameters({...p,ratio:'21:9'},s,defaults).ratio,'21:9');
assert.throws(()=>doubaoTasks({...p,ratio:'2.35:1',shots:[s]},[s.id],defaults),/不支持项目画幅/);
