import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
const dir = 'work/video-context-test';
await fs.mkdir(dir, { recursive: true });
for (const name of ['studio','dialogue-timeline', 'dialogue', 'video-performance', 'video-context', 'video-request', 'video-voice']) {
 const code=ts.transpileModule(await fs.readFile(`lib/${name}.ts`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");
 await fs.writeFile(`${dir}/${name}.mjs`,code);
}
const imp=n=>import(pathToFileURL(path.resolve(dir,n+'.mjs')).href);
const {newProject,newShot}=await imp('studio');
const {videoReferences,composeVideoContext,videoVoiceBindings}=await imp('video-context');
const {finalVideoPrompt,videoReferenceError,validateVideoBindings}=await imp('video-request');
const p=newProject('视频资料组合');p.style='写实电影';p.ratio='9:16';
const image=id=>({id,url:`/api/media/${id}`,name:`${id}.png`,type:'image/png'});
const role={id:'role-a',kind:'人物',name:'石头',description:'黑发男孩',image:image('role-image'),attributes:{声音资产:'voice-a'}};
const scene={id:'scene-a',kind:'场景',name:'卧室',description:'木床在左',image:image('scene-image')};
const prop={id:'prop-a',kind:'道具',name:'帽子',description:'红帽',image:image('prop-image')};
const clothing={id:'clothing-a',kind:'服饰',name:'西装',description:'灰色儿童西装',referenceImage:image('clothing-image'),attributes:{所属角色:'石头'}};
p.assets=[role,scene,prop,clothing,{id:'voice-a',kind:'声音',name:'清亮童声',description:'童声'}, {id:'other',kind:'人物',name:'无关人物',description:'不可带入本镜头',image:image('other-image')}];
const s=newShot();s.title='穿衣出门';s.scene='卧室';s.character='石头';s.references=['role-a','scene-a','prop-a','clothing-a'];s.blockingImage=image('blocking-image');
s.lines=[{id:'line-1',kind:'台词',speaker:'石头',emotion:'开心',voiceName:'',text:'我准备好了。'},{id:'line-2',kind:'旁白',speaker:'旁白',emotion:'平静',voiceName:'叙述音色',text:'他推开门。'}];s.dialogue=s.lines.map(l=>l.text).join('\n');
p.shots=[s];
const refs=videoReferences(p,s);
assert.deepEqual(refs.map(r=>r.mediaId),['role-image','scene-image','prop-image','clothing-image','blocking-image']);
assert.match(refs[3].label,/所属角色：石头/);
assert(!JSON.stringify(refs).includes('other-image'));
const make=(rs=refs,settings={ratio:'9:16',resolution:'1080p',duration:10})=>({projectId:p.id,targetId:s.id,target:'video',prompt:composeVideoContext(p,s,'抬手拿帽子，推门走出卧室。',settings),...settings,size:'2K',referenceIds:rs.map(r=>r.mediaId),referenceBindings:rs.map(({mediaId,label})=>({mediaId,label}))});
const input=make();input.voiceBindings=videoVoiceBindings(p,s);const prompt=finalVideoPrompt(input,{kind:'video',protocol:'ark-video',model:'doubao-seedance-1-5-pro-251215'});
for(const part of ['写实电影','9:16','1080p','1080x1920','10秒','黑发男孩','木床在左','红帽','灰色儿童西装','说话人：石头（@图1）','音色设定：清亮童声','我准备好了。','旁白｜说话人：旁白','站位约束'])assert(prompt.includes(part),part);
refs.forEach((r,i)=>assert(prompt.includes(`@图${i+1}（参考图${i+1}）：`)));
assert(!prompt.includes('不可带入本镜头'));
const custom=[refs[4],refs[0]];
const ordered=finalVideoPrompt(make(custom));assert(ordered.includes('@图1（参考图1）：本分镜/'));assert(ordered.includes('@图2（参考图2）：角色/石头（@图2）'));
assert(!ordered.includes('参考图3：'));
assert.throws(()=>validateVideoBindings({...input,referenceBindings:[...input.referenceBindings].reverse()}),/不一致/);
assert.throws(()=>validateVideoBindings({...input,referenceIds:['role-image','role-image'],referenceBindings:[refs[0],refs[0]]}),/不一致/);
assert.throws(()=>finalVideoPrompt({...input,prompt:'长'.repeat(10000)}),/超过10000/);
assert.match(finalVideoPrompt(make([])),/未发送图片/);
assert.match(finalVideoPrompt({...make([]),firstFrameId:'custom-first',referenceBindings:[{mediaId:'custom-first',label:'自定义首帧'}]}),/@图1（首帧图）：自定义首帧/);
const larger={...input,referenceIds:Array.from({length:8},(_,i)=>`r${i}`)};
assert.match(videoReferenceError({protocol:'heima-video',model:'grok'},larger),/最多支持7张/);
assert.match(videoReferenceError({protocol:'chat-video',model:'firefly-veo31-4s-16x9-720p'},{...input,referenceIds:['a']}),/首尾帧/);
assert.equal(videoReferenceError({protocol:'chat-video',model:'firefly-veo31-ref-4s-16x9-720p'},{...input,referenceIds:['a','b','c']}),'');
assert.match(finalVideoPrompt(make(refs,{ratio:'16:9',resolution:'720p',duration:6})),/1280x720/);
clothing.referenceImage=role.image;
const dedup=videoReferences(p,s);assert.equal(dedup.length,4);assert(dedup[0].label.includes('角色/石头')&&dedup[0].label.includes('服饰/西装'));
// Legacy timelines keep their sound effects and explicit timing in addition to parsed speaker bindings.
s.lines=undefined;s.dialogue='0—4秒：石头：我回来了。\n音效：开门声。';assert.match(composeVideoContext(p,s,'开门',input),/0—4秒：开门声/);
s.references=s.references.filter(id=>id!=='role-a');assert(videoReferences(p,s).some(r=>r.mediaId==='role-image'),'explicit speaker binding contributes its unique role');
console.log('PASS video context: all bound asset kinds, clothing ownership, speaker/voice mapping, legacy audio, settings, image order, shared-image labels, custom subset, first frame, limits and unrelated asset exclusion.');
const {voiceCapability,planVideoVoices}=await imp('video-voice');
const sound=p.assets.find(a=>a.id==='voice-a');sound.audio={...image('voice-file'),type:'audio/wav'};
s.references.push('role-a');s.lines=[{id:'empty',kind:'台词',speaker:'',voiceName:'',emotion:'',text:''},{id:'spoken',kind:'台词',speaker:'石头',voiceName:'叙述音色',emotion:'平静',text:'继续。'}];s.dialogue=s.lines.map(l=>l.text).join('\n');
const vb=videoVoiceBindings(p,s);
assert.equal(vb[0].mediaId,'voice-file');assert.match(vb[1].scope,/台词第1条/);assert.equal(vb[1].mediaId,undefined,'unresolved line override must not use another voice sample');
const audioModel={kind:'video',protocol:'ark-video',model:'doubao-seedance-2-0-260128'};
const vi={...make(),voiceBindings:vb};
assert.equal(voiceCapability(audioModel),'audio');assert.equal(voiceCapability({...audioModel,model:'doubao-seedance-1-5-pro-251215'}),'text');assert.equal(voiceCapability({...audioModel,model:'minimax_h3_no_audios'}),'none');
assert.equal(voiceCapability({...audioModel,model:'ep-123',voiceReference:'text'}),'text');
const vp=planVideoVoices(audioModel,vi);assert.equal(vp.samples.length,1);assert.equal(vp.bindings.length,2);
assert.equal(planVideoVoices(audioModel,{...vi,voiceBindings:[...vb,vb[0]]}).samples.length,1,'shared audio samples are sent once with all associations');
assert.equal(planVideoVoices(audioModel,{...vi,referenceIds:[]}).mode,'text');
assert.equal(planVideoVoices(audioModel,{...vi,voiceBindings:[{...vb[0],mediaType:'audio/ogg'}]}).samples.length,0);
assert(!finalVideoPrompt(vi,{...audioModel,model:'minimax_h3_no_audios'}).includes('清亮童声'));
const unknown=finalVideoPrompt(vi,{...audioModel,model:'ep-123'});assert(!unknown.includes('voice-a'));assert(unknown.includes('继续。'));
console.log('PASS voice role defaults, per-line overrides, blank-line numbering, unknown/silent omission, explicit endpoint settings, sample deduplication and unsupported sample fallback.');
