import type { GenerationInput, ModelConfig } from './models';
import {
  validateVoiceBindings,
  planVideoVoices,
  voicePrompt,
} from './video-voice';

export type VideoReferenceBinding = { mediaId: string; label: string };
export function videoDimensions(ratio: string, resolution: string) {
  const [w, h] = ratio.split(':').map(Number);
  const short = Number.parseInt(resolution, 10);
  const scale = short / Math.min(w, h);
  return `${Math.round((w * scale) / 2) * 2}x${Math.round((h * scale) / 2) * 2}`;
}
export function validateVideoBindings(input: GenerationInput) {
  if (input.referenceBindings === undefined) return;
  const ids = input.firstFrameId ? [input.firstFrameId] : input.referenceIds;
  if (
    input.target !== 'video' ||
    !Array.isArray(input.referenceBindings) ||
    input.referenceBindings.length !== ids.length ||
    new Set(ids).size !== ids.length ||
    input.referenceBindings.some(
      (b, i) =>
        !b ||
        b.mediaId !== ids[i] ||
        typeof b.label !== 'string' ||
        !b.label.trim() ||
        b.label.length > 1200,
    )
  ) {
    throw Error('参考图与资产标注不一致，请重新打开生成窗口。');
  }
}
export function videoReferenceError(
  model: ModelConfig | undefined,
  input: Pick<
    GenerationInput,
    'referenceIds' | 'firstFrameId' | 'referenceBindings'
  >,
) {
  const count = input.referenceIds.length;
  const max =
    model?.protocol === 'heima-minimax'
      ? 8
      : model?.protocol === 'heima-video'
        ? 7
        : model?.protocol === 'chat-video' &&
            model.model.startsWith('firefly-veo31-')
          ? model.model.includes('-ref-')
            ? 3
            : 2
          : 9;
  if (count > max)
    return `已组合${count}张参考图，当前模型最多支持${max}张。请改用支持更多参考图的模型，或切换自选模式调整；不会自动丢弃图片。`;
  if (
    count &&
    input.referenceBindings &&
    model?.protocol === 'chat-video' &&
    model.model.startsWith('firefly-veo31-') &&
    !model.model.includes('-ref-')
  ) {
    return '当前 VEO 型号按首尾帧处理图片，不能把角色、场景等资料当作首尾帧。请选择参考图型号，或明确使用自定义首帧模式。';
  }
  return '';
}

// Resolve against the final attachment array, after selection and deduplication.
// The text labels are generated by videoReferences; do not rely on library order.
export function numberVideoImages(
  text: string,
  bindings: VideoReferenceBinding[] = [],
) {
  const protectedLines: string[] = [];
  let body = text.replace(
    /^原台词：.*$/gm,
    (line) => `⟦SPOKEN${protectedLines.push(line) - 1}⟧`,
  );
  const ids = new Map<string, number>();
  const names = new Map<string, Set<number>>();
  bindings.forEach((binding, i) => {
    for (const m of binding.label.matchAll(
      /(?:角色|场景|道具|服饰|站位图|风格)\/(.+?)（资产ID：([^）]+)）/g,
    )) {
      ids.set(m[2], i + 1);
      const choices = names.get(m[1]) || new Set<number>();
      choices.add(i + 1);
      names.set(m[1], choices);
    }
  });
  const blockingIndex = bindings.findIndex((b) =>
    b.label.includes(' 的站位图；'),
  );
  if (blockingIndex >= 0)
    body = body.replaceAll(
      '本分镜站位图',
      `本分镜站位图（@图${blockingIndex + 1}）`,
    );
  const aliases = new Map<string, number>();
  for (const [name, choices] of names) {
    if (choices.size !== 1) continue;
    const index = [...choices][0];
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const pattern = new RegExp(
      escaped + '\\s*[（(]\\s*(@[A-Za-z0-9_\\\\-]+)\\s*[)）]',
      'g',
    );
    for (const match of body.matchAll(pattern))
      aliases.set(match[1].replaceAll('\\_', '_'), index);
  }
  body = body.replace(/（(?:角色)?资产ID：([^）]+)）/g, (_, id) =>
    ids.has(id) ? `（@图${ids.get(id)}）` : '（仅文字设定，未附参考图）',
  );
  body = body.replace(
    /@(role|scene|prop|costume|clothing)[A-Za-z0-9_\\-]+/g,
    (token) => {
      const key = token.replaceAll('\\_', '_');
      return aliases.has(key)
        ? `@图${aliases.get(key)}`
        : '仅文字设定，未附参考图';
    },
  );
  return body.replace(/⟦SPOKEN(\d+)⟧/g, (_, i) => protectedLines[Number(i)]);
}
export const videoFidelityRules = `【必须遵守的对白、画面与声音规则】
严格按原剧本台词清单逐字制作。不得擅自增删、改写或续写对白，不得把说明文字读出来，不交换说话人，不额外重复台词，不添加原剧本之外的旁白、感叹词或其他人声。情绪只影响表演，不能改变文字。画内说话者口型对应本人台词；画外音不错误对口型。若时长不足，返回无法完成的原因，不通过改词、漏字或不自然加速凑时长。
画面不得出现任何文字、字幕、标题、数字、字母、标识或水印；参考图片自带的文字一律不复现。日历等道具仅保留无文字网格与必要圈画记号，不生成日期数字或可读内容。
不配背景音乐，不加配乐、歌曲或节奏铺底。只保留原剧本对白及与动作一致的必要同期音效、环境声。旧描述中的字幕、文字与配乐要求作废。`;

export function finalVideoPrompt(input: GenerationInput, model?: ModelConfig) {
  validateVoiceBindings(input);
  const voices = planVideoVoices(model, input);
  if (voices.error) throw Error(voices.error);
  validateVideoBindings(input);
  if (
    input.referenceBindings === undefined &&
    input.voiceBindings === undefined
  ) {
    const plain = `${numberVideoImages(input.prompt)}\n\n${videoFidelityRules}`;
    if (plain.length > 10000)
      throw Error('组合后的提示词超过10000字，请精简镜头内容；不会截断台词。');
    return plain;
  }
  const legend = input.referenceBindings?.length
    ? input.referenceBindings
        .map(
          (b, i) =>
            `@图${i + 1}（${input.firstFrameId ? '首帧图' : `参考图${i + 1}`}）：${b.label}`,
        )
        .join('\n')
    : '本次未发送图片，仅使用文字设定；不要假定看到了参考图。';
  const prompt = [
    input.prompt,
    `【实际发送的图片对应表】\n${legend}`,
    voicePrompt(voices),
    '图片编号严格对应本次附件顺序。同一图片列出多个用途时共同参考；分别保持人物外观、场景空间、道具形态与服装归属，站位图仅说明本镜头空间关系。不得混淆角色、交换服装或将角色设定图当作场景。',
    videoFidelityRules,
  ]
    .filter(Boolean)
    .join('\n\n');
  if (prompt.length > 10000)
    throw Error(
      '组合后的提示词超过10000字，请精简镜头内容或资产描述后提交；不会截断台词或参考关系。',
    );
  return numberVideoImages(prompt, input.referenceBindings);
}
